//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogNatomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRelationship
    {
        public int relationshipid { get; set; }
        public int traineeid { get; set; }
        public int trainerid { get; set; }
        public string recommendedpose { get; set; }
        public Nullable<int> durationinminutes { get; set; }
    
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
