//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogNatomy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.ClientRelationships = new HashSet<ClientRelationship>();
        }
    
        public int traineeid { get; set; }
        public string traineename { get; set; }
        public Nullable<int> trainerid { get; set; }
        public Nullable<int> traineeheight { get; set; }
        public Nullable<int> traineeweight { get; set; }
        public Nullable<int> traineeage { get; set; }
        public int fitnesslevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRelationship> ClientRelationships { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
